# Generated by Django 5.1.7 on 2025-03-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_image_post_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description that appears on the home page', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='The full content of your blog post'),
        ),
    ]
