# Generated by Django 5.1.7 on 2025-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spam_words',
            field=models.TextField(blank=True, help_text='Enter spam words separated by commas'),
        ),
    ]
